import type { ProductType } from '@/models/admin/host/festival'; 

// 삐약! ProductType을 사용해서 더미 데이터를 만듭니다!
export const dummyProducts: ProductType[] = [
    {
        id: 1,
        fname: '뮤지컬 갈라 콘서트',
        fcast: ["카이", "조규현", "최재림"],
        businessName: 'yg',
        genrenm: '뮤지컬/연극',
        fage: '전체',
        fcltynm: '세종문화회관',
        faddress: '서울시 종로구',
        fdto: '2025-08-20',
        fdfrom: '2025-08-25',
        story: '삐약! 콘서트에 대한 상세 설명입니다.',
        runningTime: '120분',
        availableNOP: '1000',
        ticketPrice: '80000',
        maxPurchase: '4장',
        fticketPick: '현장 수령(QR)',
        festivalSchedules: [{ dayOfWeek: 'FRI', time: '19:00' }],
        posterFile: null,
        contentFile: [],
        hostId: 112,
    },
    {
        id: 2,
        fname: 'K-POP 아이돌 콘서트',
        fcast: ["카이", "조규현", "최재림"],
        businessName: 'sm',
        genrenm: '대중음악',
        fage: '12세 이상',
        fcltynm: '올림픽공원 체조경기장',
        faddress: '서울시 송파구',
        fdto: '2025-09-10',
        fdfrom: '2025-09-12',
        story: '삐약! 아이돌 콘서트에 대한 상세 설명입니다.',
        runningTime: '150분',
        availableNOP: '5000',
        ticketPrice: '100000',
        maxPurchase: '2장',
        fticketPick: '배송&현장 수령(QR)',
        festivalSchedules: [{ dayOfWeek: 'SAT', time: '18:00' }],
        posterFile: null,
        contentFile: [],
        hostId: 111,
    },
];